$(inherited)
${PODS_ROOT}/GoogleWebRTC/Frameworks/frameworks
${PODS_CONFIGURATION_BUILD_DIR}/Alamofire
${PODS_CONFIGURATION_BUILD_DIR}/KeychainAccess
${PODS_CONFIGURATION_BUILD_DIR}/SDWebImage
${PODS_CONFIGURATION_BUILD_DIR}/Socket.IO-Client-Swift
${PODS_CONFIGURATION_BUILD_DIR}/Starscream
${PODS_CONFIGURATION_BUILD_DIR}/Toast-Swift
